DROP DATABASE RepelDB;
CREATE DATABASE RepelDB;
USE RepelDB;
CREATE TABLE Users (
    userID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(500) NOT NULL,
    mail VARCHAR(64) NOT NULL,
    privilege INT UNSIGNED NOT NULL,
    creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    modificationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (userID)
);

CREATE TABLE Posts (
    postID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    authorID INT UNSIGNED NOT NULL,
    content TEXT NOT NULL,
    anonimity INT(1) UNSIGNED NOT NULL,
    creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    modificationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (postID),
    FOREIGN KEY (authorID)
        REFERENCES Users (userID)
);
CREATE TABLE Questions (
    questionID INT UNSIGNED NOT NULL,
    creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    modificationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (questionID),
    FOREIGN KEY (questionID)
        REFERENCES Posts (postID)
);
CREATE TABLE Answers (
    answerID INT UNSIGNED NOT NULL,
    questionID INT UNSIGNED NOT NULL,
    creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    modificationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (answerID),
    FOREIGN KEY (answerID)
        REFERENCES Posts (postID),
    FOREIGN KEY (questionID)
        REFERENCES Questions (questionID)
);

CREATE TABLE Stars (
    starID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    userID INT UNSIGNED NOT NULL,
    questionID INT UNSIGNED NOT NULL,
    creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    modificationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (starID),
    FOREIGN KEY (userID)
        REFERENCES Users (userID),
    FOREIGN KEY (questionID)
        REFERENCES Questions (questionID)
);
CREATE TABLE Votes (
    voteID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    userID INT UNSIGNED NOT NULL,
    answerID INT UNSIGNED NOT NULL,
    creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    modificationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (voteID),
    FOREIGN KEY (userID)
        REFERENCES Users (userID),
    FOREIGN KEY (answerID)
        REFERENCES Answers (answerID)
);
